### ISSUE TITLE
WebUI crahses when loading "available versions"

### ISSUE THREAD

**Issue by mrhund** [j-a-n/homematic-addon-lgtv#1]
When going to settings to check the Add-Ons and the available version the WebUI crashes when trying to load the last available version for this addon.

1) There is a blue bar in the window (see screenshot)
2) The WebUI crahes and reloads from the starting scrren (blue window with CCU Logo)

![grafik](https://user-images.githubusercontent.com/27058411/40607437-d38184d0-6268-11e8-9e52-c88149351fac.png)

**Comment by j-a-n** [comment]
I cannot reproduce the problem. Did you try another browser?

**Comment by mrhund** [comment]
Yes, you are right - crash only happens in Firefox on Windows. 

Works with Edge on Windows and Safari on iPad and Internet Explorer on Windows. With these browsers nothing is shown in the "availbale version" window.

**Comment by j-a-n** [comment]
I am unable to reproduce the problem

**Comment by j-a-n** [comment]
Fixed in 0.8.10
