### ISSUE TITLE
Don't send pause if stream is still paused

### ISSUE THREAD

**Issue by ggzengel** [j-a-n/homematic-addon-lgtv#2]
I pause my TV if the door bell rings. If the door bell is used twice the stream will play again.

Is it possible to check stream status before sending a pause event?

**Comment by j-a-n** [comment]
I do not know any possibility to get the stream status.
A simple solution could be to always send an play command before the pause command.

**Comment by ggzengel** [comment]
I will try this.
Thanks.

**Comment by ggzengel** [comment]
Without a delay between play and pause the stream will play with every second event.
I put some (4) text messages between them for a delay.

That's how it works:

```
system.Exec("/usr/local/addons/lgtv/lgtv.tcl 1 play");
system.Exec("/usr/local/addons/lgtv/lgtv.tcl 1 show_message 'Palim Palim'");
system.Exec("/usr/local/addons/lgtv/lgtv.tcl 1 show_message ''");
system.Exec("/usr/local/addons/lgtv/lgtv.tcl 1 show_message ''");
system.Exec("/usr/local/addons/lgtv/lgtv.tcl 1 show_message ''");
system.Exec("/usr/local/addons/lgtv/lgtv.tcl 1 pause");
```
